[package]
name = "coquerythmo"
version = "1.4.0"
edition = "2021"

[dependencies]
winit = "0.29"
pollster = "0.3"
env_logger = "0.11"
log = "0.4"
wgpu = "29.0.1"
glyphon = { git = "https://github.com/RuairidhWilliamson/glyphon", rev = "45a4a34" }
bytemuck = { version = "1", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
dirs = "6"
resvg = "0.44"
rfd = "0.15"
rodio = "0.20"
rust_socketio = "0.6"
rand = "0.8"
base64 = "0.22"
hypher = "0.1"
ureq = { version = "3", features = ["json"] }

[build-dependencies]
winres = "0.1"
