//! Non-interactive delivery exports for an active bande rythmo.
//!
//! This module deliberately contains no UI or video-rendering orchestration.  It
//! turns a [`Project`] into delivery documents and delegates audio transcoding
//! to FFmpeg.  Callers that manage several languages can invoke the same
//! functions once per language/project.

use crate::export::ProjectData;
use crate::media_binary;
use crate::project::Project;
use crate::rythmo_line::{MarkerKind, RythmoLine};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as FmtWrite;
use std::io::Read;
use std::path::Path;
use std::process::Stdio;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

/// Error returned when an FFmpeg delivery was cancelled by its caller.
pub const DELIVERY_EXPORT_CANCELLED_MESSAGE: &str = "Export canceled";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SubtitleFormat {
    Json,
    Srt,
    Ass,
    Detx,
}

impl SubtitleFormat {
    pub fn extension(self) -> &'static str {
        match self {
            Self::Json => "json",
            Self::Srt => "srt",
            Self::Ass => "ass",
            Self::Detx => "detx",
        }
    }
}

/// Export one active bande rythmo to any supported subtitle/interchange format.
pub fn export_subtitle(
    project: &Project,
    fps: f64,
    output: &Path,
    language_name: &str,
    format: SubtitleFormat,
) -> Result<(), String> {
    match format {
        SubtitleFormat::Json => export_json(project, fps, output),
        SubtitleFormat::Srt => export_srt(project, fps, output),
        SubtitleFormat::Ass => export_ass(project, fps, output, language_name),
        SubtitleFormat::Detx => export_detx(project, fps, output, language_name),
    }
}

/// Build the legacy-compatible JSON representation through [`ProjectData`].
pub fn json_document(project: &Project, fps: f64) -> Result<String, String> {
    validate_fps(fps)?;
    let mut data = ProjectData::from_project(project, fps);
    // A delivery JSON represents the selected bande only. The project archive
    // remains the place where the complete multilingual project is stored.
    data.languages.clear();
    data.active_language_id = None;
    serde_json::to_string_pretty(&data).map_err(|error| format!("JSON serialize error: {error}"))
}

pub fn export_json(project: &Project, fps: f64, output: &Path) -> Result<(), String> {
    write_text(output, &json_document(project, fps)?)
}

/// Build a UTF-8 SubRip document. Lines are sorted chronologically and invalid
/// or empty lines are omitted.
pub fn srt_document(project: &Project, fps: f64) -> Result<String, String> {
    validate_fps(fps)?;
    let mut document = String::new();
    for (index, line) in delivery_lines(project).into_iter().enumerate() {
        let (start_ms, end_ms) = subtitle_milliseconds(line, fps);
        writeln!(document, "{}", index + 1).expect("String writes cannot fail");
        writeln!(
            document,
            "{} --> {}",
            srt_timestamp(start_ms),
            srt_timestamp(end_ms)
        )
        .expect("String writes cannot fail");
        document.push_str(&normalized_text(&line.text));
        document.push_str("\n\n");
    }
    Ok(document.replace('\n', "\r\n"))
}

pub fn export_srt(project: &Project, fps: f64, output: &Path) -> Result<(), String> {
    write_text(output, &srt_document(project, fps)?)
}

/// Build an Advanced SubStation Alpha document. A style is emitted per role so
/// character colours survive the export; the ASS `Name` field also carries the
/// role name.
pub fn ass_document(project: &Project, fps: f64, language_name: &str) -> Result<String, String> {
    validate_fps(fps)?;
    let lines = delivery_lines(project);
    let mut roles = BTreeMap::<String, ([f32; 4], String)>::new();
    for line in &lines {
        let next_index = roles.len() + 1;
        roles
            .entry(line.character_name.clone())
            .or_insert_with(|| (line.character_color, format!("Role{next_index}")));
    }

    let title = if language_name.trim().is_empty() {
        "Coquerythmo".to_string()
    } else {
        format!("Coquerythmo - {}", language_name.trim())
    };
    let mut document = format!(
        "[Script Info]\n; Generated by Coquerythmo\nTitle: {}\nScriptType: v4.00+\nWrapStyle: 0\nScaledBorderAndShadow: yes\nPlayResX: 1920\nPlayResY: 1080\nYCbCr Matrix: TV.709\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,Arial,54,&H00FFFFFF,&H0000FFFF,&H00101010,&H80000000,0,0,0,0,100,100,0,0,1,2,0,2,70,70,48,1\n",
        ass_header_field(&title)
    );
    for (name, (color, style)) in &roles {
        writeln!(
            document,
            "Style: {},Arial,54,{},{},&H00101010,&H80000000,0,0,0,0,100,100,0,0,1,2,0,2,70,70,48,1",
            style,
            ass_color(*color),
            ass_color([1.0, 1.0, 0.0, color[3]])
        )
        .expect("String writes cannot fail");
        let _ = name;
    }
    document.push_str(
        "\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n",
    );
    for line in lines {
        let (start_ms, end_ms) = subtitle_milliseconds(line, fps);
        let style = roles
            .get(&line.character_name)
            .map(|(_, style)| style.as_str())
            .unwrap_or("Default");
        writeln!(
            document,
            "Dialogue: 0,{},{},{},{},0,0,0,,{}",
            ass_timestamp(start_ms),
            ass_timestamp(end_ms),
            style,
            ass_header_field(&line.character_name),
            ass_text(&line.text)
        )
        .expect("String writes cannot fail");
    }
    Ok(document.replace('\n', "\r\n"))
}

pub fn export_ass(
    project: &Project,
    fps: f64,
    output: &Path,
    language_name: &str,
) -> Result<(), String> {
    write_text(output, &ass_document(project, fps, language_name)?)
}

/// Build the XML dialect understood by Coquerythmo's Cappella DETX importer.
/// Role, loop and shot metadata are retained; unsupported markers are omitted.
pub fn detx_document(project: &Project, fps: f64, language_name: &str) -> Result<String, String> {
    validate_fps(fps)?;
    let lines = delivery_lines(project);
    let mut roles = BTreeMap::<String, ([f32; 4], String)>::new();
    for line in &lines {
        let next_index = roles.len() + 1;
        roles
            .entry(line.character_name.clone())
            .or_insert_with(|| (line.character_color, format!("role_{next_index}")));
    }
    for character in project.known_characters() {
        let next_index = roles.len() + 1;
        roles
            .entry(character.name.clone())
            .or_insert_with(|| (character.color, format!("role_{next_index}")));
    }

    let mut document =
        String::from("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<detx>\n  <header>\n");
    writeln!(
        document,
        "    <language name=\"{}\" />",
        xml_escape(language_name.trim())
    )
    .expect("String writes cannot fail");
    writeln!(document, "    <framerate value=\"{fps}\" />").expect("String writes cannot fail");
    document.push_str("  </header>\n  <roles>\n");
    for (name, (color, id)) in &roles {
        writeln!(
            document,
            "    <role id=\"{}\" name=\"{}\" color=\"{}\" />",
            xml_escape(id),
            xml_escape(name),
            rgb_hex(*color)
        )
        .expect("String writes cannot fail");
    }
    document.push_str("  </roles>\n  <body>\n");

    let mut markers: Vec<_> = project
        .markers()
        .iter()
        .filter(|marker| matches!(marker.kind, MarkerKind::Boucle | MarkerKind::SceneChange))
        .collect();
    markers.sort_by_key(|marker| marker.frame);
    for marker in markers {
        let tag = if marker.kind == MarkerKind::Boucle {
            "loop"
        } else {
            "shot"
        };
        writeln!(
            document,
            "    <{tag} timecode=\"{}\" />",
            frame_timecode(marker.frame, fps)
        )
        .expect("String writes cannot fail");
    }

    for line in lines {
        let role = roles
            .get(&line.character_name)
            .map(|(_, id)| id.as_str())
            .unwrap_or("role_1");
        let track = nearest_detx_track(line.y_slot);
        let voice = if is_voice_off(&line.note) {
            " voice=\"off\""
        } else {
            ""
        };
        writeln!(
            document,
            "    <line role=\"{}\" track=\"{}\"{}>",
            xml_escape(role),
            track,
            voice
        )
        .expect("String writes cannot fail");
        writeln!(
            document,
            "      <lipsync timecode=\"{}\" type=\"in_open\" />",
            frame_timecode(line.start_frame, fps)
        )
        .expect("String writes cannot fail");
        writeln!(
            document,
            "      <text>{}</text>",
            xml_escape(&single_line_text(&line.text))
        )
        .expect("String writes cannot fail");
        writeln!(
            document,
            "      <lipsync timecode=\"{}\" type=\"out_open\" />",
            frame_timecode(line.end_frame(), fps)
        )
        .expect("String writes cannot fail");
        document.push_str("    </line>\n");
    }
    document.push_str("  </body>\n</detx>\n");
    Ok(document)
}

pub fn export_detx(
    project: &Project,
    fps: f64,
    output: &Path,
    language_name: &str,
) -> Result<(), String> {
    write_text(output, &detx_document(project, fps, language_name)?)
}

/// Build an RFC 4180-compatible cross-reference CSV. The UTF-8 BOM makes the
/// result open reliably in common spreadsheet applications.
pub fn cross_reference_csv_document(
    project: &Project,
    fps: f64,
    language_name: &str,
) -> Result<String, String> {
    validate_fps(fps)?;
    let loop_starts = loop_starts(project);
    let mut csv =
        String::from("\u{feff}Language,Loop,In,Out,Duration,Character,Voice actors,Text,Note\r\n");
    for line in delivery_lines(project) {
        let fields = [
            language_name.to_string(),
            loop_number(line.start_frame, &loop_starts).to_string(),
            frame_timecode(line.start_frame, fps),
            frame_timecode(line.end_frame(), fps),
            frame_timecode(line.duration_frames, fps),
            line.character_name.clone(),
            line.voice_actor_names.join(" | "),
            normalized_text(&line.text),
            normalized_text(&line.note),
        ];
        csv.push_str(
            &fields
                .iter()
                .map(|field| csv_field(field))
                .collect::<Vec<_>>()
                .join(","),
        );
        csv.push_str("\r\n");
    }
    Ok(csv)
}

pub fn export_cross_reference_csv(
    project: &Project,
    fps: f64,
    output: &Path,
    language_name: &str,
) -> Result<(), String> {
    write_text(
        output,
        &cross_reference_csv_document(project, fps, language_name)?,
    )
}

fn validate_fps(fps: f64) -> Result<(), String> {
    if fps.is_finite() && fps > 0.0 {
        Ok(())
    } else {
        Err(format!("Invalid FPS for delivery export: {fps}"))
    }
}

fn write_text(output: &Path, text: &str) -> Result<(), String> {
    std::fs::write(output, text.as_bytes())
        .map_err(|error| format!("Cannot write {}: {error}", output.display()))
}

fn delivery_lines(project: &Project) -> Vec<&RythmoLine> {
    let mut lines: Vec<_> = project
        .lines()
        .filter(|line| {
            line.duration_frames > 0 && line.end_frame() > 0 && !line.text.trim().is_empty()
        })
        .collect();
    lines.sort_by_key(|line| (line.start_frame, line.end_frame(), line.id));
    lines
}

fn subtitle_milliseconds(line: &RythmoLine, fps: f64) -> (u64, u64) {
    let start = ((line.start_frame.max(0) as f64 / fps) * 1000.0).round() as u64;
    let mut end = ((line.end_frame().max(0) as f64 / fps) * 1000.0).round() as u64;
    if end <= start {
        end = start + 1;
    }
    (start, end)
}

fn srt_timestamp(milliseconds: u64) -> String {
    let hours = milliseconds / 3_600_000;
    let minutes = (milliseconds / 60_000) % 60;
    let seconds = (milliseconds / 1_000) % 60;
    let millis = milliseconds % 1_000;
    format!("{hours:02}:{minutes:02}:{seconds:02},{millis:03}")
}

fn ass_timestamp(milliseconds: u64) -> String {
    let centiseconds = (milliseconds + 5) / 10;
    let hours = centiseconds / 360_000;
    let minutes = (centiseconds / 6_000) % 60;
    let seconds = (centiseconds / 100) % 60;
    let centis = centiseconds % 100;
    format!("{hours}:{minutes:02}:{seconds:02}.{centis:02}")
}

fn normalized_text(text: &str) -> String {
    text.trim().replace("\r\n", "\n").replace('\r', "\n")
}

fn single_line_text(text: &str) -> String {
    normalized_text(text)
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .collect::<Vec<_>>()
        .join(" ")
}

fn ass_header_field(text: &str) -> String {
    single_line_text(text).replace(',', ";")
}

fn ass_text(text: &str) -> String {
    normalized_text(text)
        .replace('\\', "\\\\")
        .replace('{', "\\{")
        .replace('}', "\\}")
        .replace('\n', "\\N")
}

fn ass_color(color: [f32; 4]) -> String {
    let byte = |component: f32| (component.clamp(0.0, 1.0) * 255.0).round() as u8;
    let alpha = 255_u8.saturating_sub(byte(color[3]));
    format!(
        "&H{alpha:02X}{:02X}{:02X}{:02X}",
        byte(color[2]),
        byte(color[1]),
        byte(color[0])
    )
}

fn rgb_hex(color: [f32; 4]) -> String {
    let byte = |component: f32| (component.clamp(0.0, 1.0) * 255.0).round() as u8;
    format!(
        "#{:02X}{:02X}{:02X}",
        byte(color[0]),
        byte(color[1]),
        byte(color[2])
    )
}

fn xml_escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

fn nearest_detx_track(y_slot: f32) -> usize {
    [0.25_f32, 0.5, 0.75, 1.0]
        .iter()
        .enumerate()
        .min_by(|(_, left), (_, right)| {
            (y_slot - **left).abs().total_cmp(&(y_slot - **right).abs())
        })
        .map(|(index, _)| index)
        .unwrap_or(1)
}

fn is_voice_off(note: &str) -> bool {
    let note = note.to_lowercase();
    note.contains("voix off") || note.contains("voice off")
}

fn frame_timecode(frame: i64, fps: f64) -> String {
    let nominal_fps = fps.round().max(1.0) as i64;
    let frame = frame.max(0);
    let hours = frame / (nominal_fps * 3600);
    let minutes = (frame / (nominal_fps * 60)) % 60;
    let seconds = (frame / nominal_fps) % 60;
    let frames = frame % nominal_fps;
    format!("{hours:02}:{minutes:02}:{seconds:02}:{frames:02}")
}

fn csv_field(field: &str) -> String {
    if field.contains([',', '"', '\r', '\n']) {
        format!("\"{}\"", field.replace('"', "\"\""))
    } else {
        field.to_string()
    }
}

fn loop_starts(project: &Project) -> Vec<i64> {
    let mut starts: Vec<_> = project
        .markers()
        .iter()
        .filter(|marker| marker.kind == MarkerKind::Boucle)
        .map(|marker| marker.frame.max(0))
        .collect();
    starts.sort_unstable();
    starts.dedup();
    if starts.is_empty() {
        // A project without explicit loop markers still has one useful
        // delivery interval. Do not synthesize an extra loop when markers do
        // exist: their numbering must remain faithful to the authored grid.
        starts.push(0);
    }
    starts
}

fn loop_number(frame: i64, starts: &[i64]) -> usize {
    starts
        .partition_point(|start| *start <= frame.max(0))
        .max(1)
}

// -- PDF reports -----------------------------------------------------------

const PDF_WIDTH: f32 = 842.0;
const PDF_HEIGHT: f32 = 595.0;
const PDF_MARGIN: f32 = 24.0;
const PDF_UNICODE_RASTER_SCALE: f32 = 4.0;

struct PdfImageMask {
    width: u32,
    height: u32,
    packed_bits: Vec<u8>,
    display_width: f32,
    display_height: f32,
    baseline_from_bottom: f32,
}

#[derive(Default)]
struct PdfCanvas {
    content: String,
    image_masks: Vec<PdfImageMask>,
}

impl PdfCanvas {
    fn text(&mut self, x: f32, y: f32, size: f32, bold: bool, text: &str) {
        if !can_encode_win_ansi(text) {
            if let Some(image) = rasterize_pdf_text(text, size, bold) {
                let image_index = self.image_masks.len() + 1;
                let image_y = y - image.baseline_from_bottom;
                writeln!(
                    self.content,
                    "/Span << /ActualText <{}> >> BDC",
                    pdf_utf16_hex(text)
                )
                .expect("String writes cannot fail");
                writeln!(
                    self.content,
                    "q 0 g {:.2} 0 0 {:.2} {x:.2} {image_y:.2} cm /Im{image_index} Do Q",
                    image.display_width, image.display_height
                )
                .expect("String writes cannot fail");
                self.content.push_str("EMC\n");
                self.image_masks.push(image);
                return;
            }
            // Even when the host has no usable glyph for the requested script,
            // never silently turn the content into question marks. Draw a
            // conventional missing-glyph grid while retaining the exact text
            // in ActualText for copy/paste and accessibility.
            writeln!(
                self.content,
                "/Span << /ActualText <{}> >> BDC",
                pdf_utf16_hex(text)
            )
            .expect("String writes cannot fail");
            let glyph_width = (size * 0.65).max(2.0);
            for index in 0..text.chars().count().min(24) {
                let glyph_x = x + index as f32 * (glyph_width + 1.0);
                writeln!(
                    self.content,
                    "q 0.35 G 0.45 w {glyph_x:.2} {:.2} {glyph_width:.2} {size:.2} re S Q",
                    y - size * 0.22
                )
                .expect("String writes cannot fail");
            }
            self.content.push_str("EMC\n");
            return;
        }

        let font = if bold { "F2" } else { "F1" };
        writeln!(
            self.content,
            "BT /{font} {size:.2} Tf 0 g 1 0 0 1 {x:.2} {y:.2} Tm ({}) Tj ET",
            pdf_string(text)
        )
        .expect("String writes cannot fail");
    }

    fn fill_rect(&mut self, x: f32, y: f32, width: f32, height: f32, gray: f32) {
        writeln!(
            self.content,
            "q {:.3} g {x:.2} {y:.2} {width:.2} {height:.2} re f Q",
            gray.clamp(0.0, 1.0)
        )
        .expect("String writes cannot fail");
    }

    fn stroke_rect(&mut self, x: f32, y: f32, width: f32, height: f32) {
        writeln!(
            self.content,
            "q 0.72 G 0.45 w {x:.2} {y:.2} {width:.2} {height:.2} re S Q"
        )
        .expect("String writes cannot fail");
    }
}

fn rasterize_pdf_text(text: &str, size: f32, bold: bool) -> Option<PdfImageMask> {
    if text.is_empty() || !size.is_finite() || size <= 0.0 {
        return None;
    }

    let measured_width = crate::vector_text::measure_project_text_width_standalone(text, size)
        .unwrap_or_else(|| text.chars().count().max(1) as f32 * size);
    let raster_size = size * PDF_UNICODE_RASTER_SCALE;
    let width = ((measured_width + 4.0) * PDF_UNICODE_RASTER_SCALE)
        .ceil()
        .clamp(1.0, 16_384.0) as u32;
    let height = (raster_size * 1.4).ceil().clamp(1.0, 4_096.0) as u32;
    let rendered = crate::vector_text::render_project_text_natural_standalone(
        text,
        raster_size,
        width,
        height,
    )?;
    if rendered.pixels.len() != width as usize * height as usize * 4 {
        return None;
    }

    let mut coverage = vec![false; width as usize * height as usize];
    for (pixel_index, pixel) in rendered.pixels.chunks_exact(4).enumerate() {
        coverage[pixel_index] = pixel[3] >= 24;
    }
    if bold {
        let original = coverage.clone();
        for y in 0..height as usize {
            for x in 0..width as usize {
                if !original[y * width as usize + x] {
                    continue;
                }
                if x + 1 < width as usize {
                    coverage[y * width as usize + x + 1] = true;
                }
                if y + 1 < height as usize {
                    coverage[(y + 1) * width as usize + x] = true;
                }
            }
        }
    }
    if !coverage.iter().any(|covered| *covered) {
        log::warn!(
            "No renderable glyph found for PDF Unicode text ({} characters)",
            text.chars().count()
        );
        return None;
    }

    let row_bytes = width.div_ceil(8) as usize;
    let mut packed_bits = vec![0_u8; row_bytes * height as usize];
    for y in 0..height as usize {
        for x in 0..width as usize {
            if coverage[y * width as usize + x] {
                packed_bits[y * row_bytes + x / 8] |= 1 << (7 - x % 8);
            }
        }
    }

    let display_width = width as f32 / PDF_UNICODE_RASTER_SCALE;
    let display_height = height as f32 / PDF_UNICODE_RASTER_SCALE;
    Some(PdfImageMask {
        width,
        height,
        packed_bits,
        display_width,
        display_height,
        baseline_from_bottom: (display_height - size).max(0.0),
    })
}

#[derive(Debug)]
struct CrossReferenceRow {
    loop_number: String,
    start: String,
    end: String,
    duration: String,
    character: String,
    voice_actors: String,
    text: String,
    note: String,
}

/// Create a minimal, dependency-free PDF containing the dialogue cross
/// reference. The returned bytes can be embedded in an archive or written by a
/// caller without creating a temporary file.
pub fn cross_reference_pdf_bytes(
    project: &Project,
    fps: f64,
    language_name: &str,
) -> Result<Vec<u8>, String> {
    validate_fps(fps)?;
    let starts = loop_starts(project);
    let rows: Vec<_> = delivery_lines(project)
        .into_iter()
        .map(|line| CrossReferenceRow {
            loop_number: loop_number(line.start_frame, &starts).to_string(),
            start: frame_timecode(line.start_frame, fps),
            end: frame_timecode(line.end_frame(), fps),
            duration: frame_timecode(line.duration_frames, fps),
            character: line.character_name.clone(),
            voice_actors: line.voice_actor_names.join(", "),
            text: single_line_text(&line.text),
            note: single_line_text(&line.note),
        })
        .collect();

    let widths = [30.0, 58.0, 58.0, 55.0, 76.0, 88.0, 329.0, 100.0];
    let headers = [
        "Loop",
        "In",
        "Out",
        "Dur.",
        "Character",
        "Actors",
        "Text",
        "Note",
    ];
    let mut pages = Vec::<PdfCanvas>::new();
    let mut page = cross_reference_page(language_name, &headers, &widths);
    let mut y = 500.0;

    if rows.is_empty() {
        page.text(
            PDF_MARGIN,
            472.0,
            9.0,
            false,
            "No dialogue lines to export.",
        );
    }

    for row in rows {
        let cells = [
            row.loop_number,
            row.start,
            row.end,
            row.duration,
            row.character,
            row.voice_actors,
            row.text,
            row.note,
        ];
        let wrapped: Vec<Vec<String>> = cells
            .iter()
            .zip(widths)
            .map(|(cell, width)| wrap_pdf_text(cell, width - 6.0, 7.0, 5))
            .collect();
        let line_count = wrapped.iter().map(Vec::len).max().unwrap_or(1).max(1);
        let row_height = (line_count as f32 * 9.0 + 6.0).max(17.0);

        if y - row_height < 38.0 {
            pages.push(page);
            page = cross_reference_page(language_name, &headers, &widths);
            y = 500.0;
        }

        let bottom = y - row_height;
        let mut x = PDF_MARGIN;
        for (column, (cell_lines, width)) in wrapped.iter().zip(widths).enumerate() {
            if column == 0 {
                page.fill_rect(x, bottom, width, row_height, 0.965);
            }
            page.stroke_rect(x, bottom, width, row_height);
            for (line_index, text) in cell_lines.iter().enumerate() {
                page.text(
                    x + 3.0,
                    y - 10.0 - line_index as f32 * 9.0,
                    7.0,
                    column == 0,
                    text,
                );
            }
            x += width;
        }
        y = bottom;
    }
    pages.push(page);
    add_pdf_footers(&mut pages);
    Ok(build_pdf(&pages))
}

pub fn export_cross_reference_pdf(
    project: &Project,
    fps: f64,
    output: &Path,
    language_name: &str,
) -> Result<(), String> {
    write_bytes(
        output,
        &cross_reference_pdf_bytes(project, fps, language_name)?,
    )
}

fn cross_reference_page(language_name: &str, headers: &[&str; 8], widths: &[f32; 8]) -> PdfCanvas {
    let mut page = PdfCanvas::default();
    page.text(
        PDF_MARGIN,
        PDF_HEIGHT - 29.0,
        16.0,
        true,
        "Dialogue cross-reference",
    );
    page.text(
        PDF_MARGIN,
        PDF_HEIGHT - 47.0,
        8.5,
        false,
        &format!("Language: {}", display_language(language_name)),
    );
    let top = 520.0;
    let height = 20.0;
    let mut x = PDF_MARGIN;
    for (header, width) in headers.iter().zip(widths) {
        page.fill_rect(x, top - height, *width, height, 0.86);
        page.stroke_rect(x, top - height, *width, height);
        page.text(x + 3.0, top - 13.0, 7.0, true, header);
        x += *width;
    }
    page
}

#[derive(Clone, Copy, Debug)]
struct LoopSpan {
    number: usize,
    start: i64,
    end: i64,
}

/// Create a loops-by-characters presence grid as a minimal PDF. A role is
/// marked when any of its lines overlaps a loop interval.
pub fn presence_grid_pdf_bytes(
    project: &Project,
    fps: f64,
    language_name: &str,
) -> Result<Vec<u8>, String> {
    validate_fps(fps)?;
    let spans = loop_spans(project);
    let mut characters = BTreeSet::<String>::new();
    for character in project.known_characters() {
        if !character.name.trim().is_empty() {
            characters.insert(character.name.clone());
        }
    }
    for line in project.lines() {
        if !line.character_name.trim().is_empty() {
            characters.insert(line.character_name.clone());
        }
    }
    let characters: Vec<_> = characters.into_iter().collect();
    let lines: Vec<_> = project.lines().collect();

    const MAX_CHARACTER_COLUMNS: usize = 10;
    const MAX_LOOP_ROWS: usize = 22;
    let character_chunks: Vec<&[String]> = if characters.is_empty() {
        vec![&[]]
    } else {
        characters.chunks(MAX_CHARACTER_COLUMNS).collect()
    };
    let span_chunks: Vec<&[LoopSpan]> = if spans.is_empty() {
        vec![&[]]
    } else {
        spans.chunks(MAX_LOOP_ROWS).collect()
    };
    let mut pages = Vec::new();

    for (character_chunk_index, character_chunk) in character_chunks.iter().enumerate() {
        for span_chunk in &span_chunks {
            let mut page = PdfCanvas::default();
            page.text(
                PDF_MARGIN,
                PDF_HEIGHT - 29.0,
                16.0,
                true,
                "Loop presence grid",
            );
            page.text(
                PDF_MARGIN,
                PDF_HEIGHT - 47.0,
                8.5,
                false,
                &format!(
                    "Language: {}   Roles {}-{} of {}",
                    display_language(language_name),
                    character_chunk_index * MAX_CHARACTER_COLUMNS + 1,
                    (character_chunk_index * MAX_CHARACTER_COLUMNS + character_chunk.len()).max(1),
                    characters.len()
                ),
            );

            let first_width = 128.0;
            let roles_width = PDF_WIDTH - PDF_MARGIN * 2.0 - first_width;
            let role_width = if character_chunk.is_empty() {
                roles_width
            } else {
                roles_width / character_chunk.len() as f32
            };
            let header_top = 520.0;
            let header_height = 42.0;
            page.fill_rect(
                PDF_MARGIN,
                header_top - header_height,
                first_width,
                header_height,
                0.86,
            );
            page.stroke_rect(
                PDF_MARGIN,
                header_top - header_height,
                first_width,
                header_height,
            );
            page.text(
                PDF_MARGIN + 4.0,
                header_top - 24.0,
                7.5,
                true,
                "Loop / time range",
            );
            let mut x = PDF_MARGIN + first_width;
            for character in *character_chunk {
                page.fill_rect(
                    x,
                    header_top - header_height,
                    role_width,
                    header_height,
                    0.86,
                );
                page.stroke_rect(x, header_top - header_height, role_width, header_height);
                for (line_index, text) in wrap_pdf_text(character, role_width - 6.0, 6.5, 3)
                    .iter()
                    .enumerate()
                {
                    page.text(
                        x + 3.0,
                        header_top - 12.0 - line_index as f32 * 8.0,
                        6.5,
                        true,
                        text,
                    );
                }
                x += role_width;
            }

            let row_height = 19.0;
            let mut top = header_top - header_height;
            if span_chunk.is_empty() {
                page.text(PDF_MARGIN, top - 24.0, 9.0, false, "No loops to export.");
            }
            for span in *span_chunk {
                let bottom = top - row_height;
                if span.number % 2 == 0 {
                    page.fill_rect(
                        PDF_MARGIN,
                        bottom,
                        PDF_WIDTH - PDF_MARGIN * 2.0,
                        row_height,
                        0.97,
                    );
                }
                page.stroke_rect(PDF_MARGIN, bottom, first_width, row_height);
                page.text(
                    PDF_MARGIN + 4.0,
                    bottom + 6.0,
                    7.0,
                    true,
                    &format!(
                        "{}  {} - {}",
                        span.number,
                        frame_timecode(span.start, fps),
                        frame_timecode(span.end, fps)
                    ),
                );
                x = PDF_MARGIN + first_width;
                for character in *character_chunk {
                    page.stroke_rect(x, bottom, role_width, row_height);
                    let present = lines.iter().any(|line| {
                        line.character_name == *character
                            && line.duration_frames > 0
                            && line.start_frame < span.end
                            && line.end_frame() > span.start
                    });
                    if present {
                        page.text(x + role_width / 2.0 - 2.5, bottom + 5.5, 8.5, true, "X");
                    }
                    x += role_width;
                }
                top = bottom;
            }
            pages.push(page);
        }
    }

    add_pdf_footers(&mut pages);
    Ok(build_pdf(&pages))
}

pub fn export_presence_grid_pdf(
    project: &Project,
    fps: f64,
    output: &Path,
    language_name: &str,
) -> Result<(), String> {
    write_bytes(
        output,
        &presence_grid_pdf_bytes(project, fps, language_name)?,
    )
}

fn loop_spans(project: &Project) -> Vec<LoopSpan> {
    let starts = loop_starts(project);
    let content_end = project
        .lines()
        .map(RythmoLine::end_frame)
        .chain(project.markers().iter().map(|marker| marker.frame))
        .max()
        .unwrap_or(1)
        .max(1);
    starts
        .iter()
        .enumerate()
        .map(|(index, start)| {
            let next_loop = starts.get(index + 1).copied();
            let next_out = project
                .markers()
                .iter()
                .filter(|marker| marker.kind == MarkerKind::Out && marker.frame > *start)
                .map(|marker| marker.frame)
                .min();
            let end = next_loop
                .into_iter()
                .chain(next_out)
                .min()
                .unwrap_or(content_end)
                .max(*start + 1);
            LoopSpan {
                number: index + 1,
                start: *start,
                end,
            }
        })
        .collect()
}

fn display_language(language_name: &str) -> &str {
    if language_name.trim().is_empty() {
        "Unspecified"
    } else {
        language_name.trim()
    }
}

fn wrap_pdf_text(text: &str, width: f32, font_size: f32, max_lines: usize) -> Vec<String> {
    let normalized = single_line_text(text);
    if normalized.is_empty() {
        return vec![String::new()];
    }
    if !can_encode_win_ansi(&normalized) {
        return wrap_unicode_pdf_text(&normalized, width, font_size, max_lines);
    }

    let max_chars = (width / (font_size * 0.53)).floor().max(1.0) as usize;

    let mut lines = Vec::<String>::new();
    let mut current = String::new();
    for word in normalized.split_whitespace() {
        let candidate_len =
            current.chars().count() + usize::from(!current.is_empty()) + word.chars().count();
        if candidate_len <= max_chars {
            if !current.is_empty() {
                current.push(' ');
            }
            current.push_str(word);
            continue;
        }
        if !current.is_empty() {
            lines.push(std::mem::take(&mut current));
        }
        let mut chunk = String::new();
        for character in word.chars() {
            chunk.push(character);
            if chunk.chars().count() == max_chars {
                lines.push(std::mem::take(&mut chunk));
            }
        }
        current = chunk;
    }
    if !current.is_empty() {
        lines.push(current);
    }
    if lines.len() > max_lines.max(1) {
        lines.truncate(max_lines.max(1));
        let last = lines.last_mut().expect("at least one PDF line");
        while last.chars().count() + 3 > max_chars && !last.is_empty() {
            last.pop();
        }
        last.push_str("...");
    }
    lines
}

fn wrap_unicode_pdf_text(text: &str, width: f32, font_size: f32, max_lines: usize) -> Vec<String> {
    let max_lines = max_lines.max(1);
    let mut lines = Vec::<String>::new();
    let mut current = String::new();

    for word in text.split_whitespace() {
        let candidate = if current.is_empty() {
            word.to_string()
        } else {
            format!("{current} {word}")
        };
        if pdf_text_width(&candidate, font_size) <= width {
            current = candidate;
            continue;
        }

        if !current.is_empty() {
            lines.push(std::mem::take(&mut current));
        }
        if pdf_text_width(word, font_size) <= width {
            current.push_str(word);
            continue;
        }

        for cluster in unicode_scalar_clusters(word) {
            let candidate = format!("{current}{cluster}");
            if !current.is_empty() && pdf_text_width(&candidate, font_size) > width {
                lines.push(std::mem::take(&mut current));
            }
            current.push_str(&cluster);
        }
    }
    if !current.is_empty() {
        lines.push(current);
    }
    if lines.is_empty() {
        lines.push(String::new());
    }

    if lines.len() > max_lines {
        lines.truncate(max_lines);
        let last = lines.last_mut().expect("at least one PDF line");
        while !last.is_empty() && pdf_text_width(&format!("{last}..."), font_size) > width {
            last.pop();
        }
        last.push_str("...");
    }
    lines
}

fn unicode_scalar_clusters(text: &str) -> Vec<String> {
    let mut clusters = Vec::<String>::new();
    for character in text.chars() {
        if is_unicode_combining_mark(character)
            || character == '\u{fe0f}'
            || character == '\u{200d}'
        {
            if let Some(last) = clusters.last_mut() {
                last.push(character);
                continue;
            }
        }
        clusters.push(character.to_string());
    }
    clusters
}

fn is_unicode_combining_mark(character: char) -> bool {
    matches!(
        character as u32,
        0x0300..=0x036f
            | 0x0483..=0x0489
            | 0x0591..=0x05bd
            | 0x05bf
            | 0x05c1..=0x05c2
            | 0x05c4..=0x05c5
            | 0x0610..=0x061a
            | 0x064b..=0x065f
            | 0x0670
            | 0x06d6..=0x06ed
            | 0x1ab0..=0x1aff
            | 0x1dc0..=0x1dff
            | 0x20d0..=0x20ff
            | 0xfe20..=0xfe2f
    )
}

fn pdf_text_width(text: &str, font_size: f32) -> f32 {
    crate::vector_text::measure_project_text_width_standalone(text, font_size)
        .unwrap_or_else(|| text.chars().count() as f32 * font_size)
}

fn add_pdf_footers(pages: &mut [PdfCanvas]) {
    let total = pages.len();
    for (index, page) in pages.iter_mut().enumerate() {
        page.text(PDF_MARGIN, 18.0, 7.0, false, "Generated by Coquerythmo");
        page.text(
            PDF_WIDTH - 72.0,
            18.0,
            7.0,
            false,
            &format!("Page {} / {total}", index + 1),
        );
    }
}

fn build_pdf(pages: &[PdfCanvas]) -> Vec<u8> {
    struct PageObjects {
        page: usize,
        content: usize,
        images: Vec<usize>,
    }

    let mut next_object = 5_usize;
    let page_objects: Vec<_> = pages
        .iter()
        .map(|page| {
            let page_object = next_object;
            let content_object = next_object + 1;
            next_object += 2;
            let images = (0..page.image_masks.len())
                .map(|_| {
                    let image_object = next_object;
                    next_object += 1;
                    image_object
                })
                .collect();
            PageObjects {
                page: page_object,
                content: content_object,
                images,
            }
        })
        .collect();

    let mut objects = Vec::<Vec<u8>>::new();
    objects.push(b"<< /Type /Catalog /Pages 2 0 R >>".to_vec());

    let kids = page_objects
        .iter()
        .map(|objects| format!("{} 0 R", objects.page))
        .collect::<Vec<_>>()
        .join(" ");
    objects.push(format!("<< /Type /Pages /Kids [{kids}] /Count {} >>", pages.len()).into_bytes());
    objects.push(
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>"
            .to_vec(),
    );
    objects.push(
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>"
            .to_vec(),
    );

    for (page, page_objects) in pages.iter().zip(&page_objects) {
        debug_assert_eq!(objects.len() + 1, page_objects.page);
        let xobjects = if page_objects.images.is_empty() {
            String::new()
        } else {
            format!(
                " /XObject << {} >>",
                page_objects
                    .images
                    .iter()
                    .enumerate()
                    .map(|(index, object)| format!("/Im{} {object} 0 R", index + 1))
                    .collect::<Vec<_>>()
                    .join(" ")
            )
        };
        objects.push(
            format!(
                "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {PDF_WIDTH:.0} {PDF_HEIGHT:.0}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >>{xobjects} >> /Contents {} 0 R >>",
                page_objects.content
            )
            .into_bytes(),
        );
        let content = page.content.as_bytes();
        let mut stream = format!("<< /Length {} >>\nstream\n", content.len()).into_bytes();
        stream.extend_from_slice(content);
        stream.extend_from_slice(b"endstream");
        objects.push(stream);

        for (image, image_object) in page.image_masks.iter().zip(&page_objects.images) {
            debug_assert_eq!(objects.len() + 1, *image_object);
            let mut stream = format!(
                "<< /Type /XObject /Subtype /Image /Width {} /Height {} /ImageMask true /BitsPerComponent 1 /Decode [1 0] /Interpolate true /Length {} >>\nstream\n",
                image.width,
                image.height,
                image.packed_bits.len()
            )
            .into_bytes();
            stream.extend_from_slice(&image.packed_bits);
            stream.extend_from_slice(b"\nendstream");
            objects.push(stream);
        }
    }

    let mut pdf = b"%PDF-1.4\n%\xE2\xE3\xCF\xD3\n".to_vec();
    let mut offsets = vec![0_usize];
    for (index, object) in objects.iter().enumerate() {
        offsets.push(pdf.len());
        pdf.extend_from_slice(format!("{} 0 obj\n", index + 1).as_bytes());
        pdf.extend_from_slice(object);
        pdf.extend_from_slice(b"\nendobj\n");
    }
    let xref_offset = pdf.len();
    pdf.extend_from_slice(format!("xref\n0 {}\n", objects.len() + 1).as_bytes());
    pdf.extend_from_slice(b"0000000000 65535 f \n");
    for offset in offsets.into_iter().skip(1) {
        pdf.extend_from_slice(format!("{offset:010} 00000 n \n").as_bytes());
    }
    pdf.extend_from_slice(
        format!(
            "trailer\n<< /Size {} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF\n",
            objects.len() + 1
        )
        .as_bytes(),
    );
    pdf
}

fn pdf_string(text: &str) -> String {
    let mut escaped = String::new();
    for byte in text
        .chars()
        .map(|character| win_ansi_byte(character).unwrap_or(b'?'))
    {
        match byte {
            b'(' => escaped.push_str("\\("),
            b')' => escaped.push_str("\\)"),
            b'\\' => escaped.push_str("\\\\"),
            0x20..=0x7e => escaped.push(byte as char),
            _ => write!(escaped, "\\{byte:03o}").expect("String writes cannot fail"),
        }
    }
    escaped
}

fn can_encode_win_ansi(text: &str) -> bool {
    text.chars()
        .all(|character| win_ansi_byte(character).is_some())
}

fn win_ansi_byte(character: char) -> Option<u8> {
    Some(match character {
        '\u{0000}'..='\u{001f}' => b' ',
        '\u{0020}'..='\u{007e}' => character as u8,
        '\u{00a0}'..='\u{00ff}' => character as u8,
        '\u{20ac}' => 0x80,
        '\u{201a}' => 0x82,
        '\u{0192}' => 0x83,
        '\u{201e}' => 0x84,
        '\u{2026}' => 0x85,
        '\u{2020}' => 0x86,
        '\u{2021}' => 0x87,
        '\u{02c6}' => 0x88,
        '\u{2030}' => 0x89,
        '\u{0160}' => 0x8a,
        '\u{2039}' => 0x8b,
        '\u{0152}' => 0x8c,
        '\u{017d}' => 0x8e,
        '\u{2018}' => 0x91,
        '\u{2019}' => 0x92,
        '\u{201c}' => 0x93,
        '\u{201d}' => 0x94,
        '\u{2022}' => 0x95,
        '\u{2013}' => 0x96,
        '\u{2014}' => 0x97,
        '\u{02dc}' => 0x98,
        '\u{2122}' => 0x99,
        '\u{0161}' => 0x9a,
        '\u{203a}' => 0x9b,
        '\u{0153}' => 0x9c,
        '\u{017e}' => 0x9e,
        '\u{0178}' => 0x9f,
        _ => return None,
    })
}

fn pdf_utf16_hex(text: &str) -> String {
    let mut encoded = String::from("FEFF");
    for unit in text.encode_utf16() {
        write!(encoded, "{unit:04X}").expect("String writes cannot fail");
    }
    encoded
}

fn write_bytes(output: &Path, bytes: &[u8]) -> Result<(), String> {
    std::fs::write(output, bytes)
        .map_err(|error| format!("Cannot write {}: {error}", output.display()))
}

// -- Audio deliveries ------------------------------------------------------

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AudioTrackKind {
    Original,
    Instrumental,
}

impl AudioTrackKind {
    pub fn label(self) -> &'static str {
        match self {
            Self::Original => "original",
            Self::Instrumental => "instrumental",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AudioDeliveryFormat {
    Mp3,
    Wav,
    Bwf,
}

impl AudioDeliveryFormat {
    pub fn extension(self) -> &'static str {
        match self {
            Self::Mp3 => "mp3",
            Self::Wav | Self::Bwf => "wav",
        }
    }
}

#[derive(Clone, Debug)]
pub struct AudioExportOptions<'a> {
    pub format: AudioDeliveryFormat,
    pub track: AudioTrackKind,
    pub language_name: &'a str,
    pub stem_name: &'a str,
    /// Optional delivery duration. When set, FFmpeg pads or trims the adjusted
    /// audio to exactly this number of project frames.
    pub duration_frames: Option<i64>,
}

impl<'a> AudioExportOptions<'a> {
    pub fn new(format: AudioDeliveryFormat, track: AudioTrackKind, language_name: &'a str) -> Self {
        Self {
            format,
            track,
            language_name,
            stem_name: track.label(),
            duration_frames: None,
        }
    }
}

#[derive(Clone, Debug)]
pub struct AudioStemExport<'a> {
    pub input: &'a Path,
    pub output: &'a Path,
    pub track: AudioTrackKind,
    pub language_name: &'a str,
    pub stem_name: &'a str,
    pub duration_frames: Option<i64>,
}

/// Transcode one source or instrumental track to MP3, WAV or BWF. The offset
/// is selected from the active project's settings according to `options.track`.
/// FFmpeg writes a sibling temporary file and only replaces `output` after a
/// successful transcode.
pub fn export_audio(
    project: &Project,
    fps: f64,
    input: &Path,
    output: &Path,
    options: &AudioExportOptions<'_>,
    cancel: &AtomicBool,
) -> Result<(), String> {
    validate_fps(fps)?;
    if cancel.load(Ordering::Relaxed) {
        return Err(DELIVERY_EXPORT_CANCELLED_MESSAGE.to_string());
    }
    if let Some(duration_frames) = options.duration_frames {
        if duration_frames <= 0 {
            return Err(format!(
                "Audio delivery duration must be positive (got {duration_frames} frames)"
            ));
        }
    }

    let offset_frames = match options.track {
        AudioTrackKind::Original => project.settings().source_audio_offset_frames,
        AudioTrackKind::Instrumental => project.settings().instrumental_audio_offset_frames,
    };
    let filter = audio_delivery_filter(offset_frames, fps, options.duration_frames);
    let temporary = temporary_audio_path(output, options.format);
    let _ = std::fs::remove_file(&temporary);

    let mut command = media_binary::command("ffmpeg");
    command
        .arg("-nostdin")
        .arg("-hide_banner")
        .arg("-i")
        .arg(input)
        .args(["-map", "0:a:0", "-vn", "-af", &filter, "-map_metadata", "0"]);

    let title = if options.stem_name.trim().is_empty() {
        options.track.label()
    } else {
        options.stem_name.trim()
    };
    command
        .arg("-metadata")
        .arg(format!("title={title}"))
        .arg("-metadata")
        .arg(format!("language={}", options.language_name.trim()));

    match options.format {
        AudioDeliveryFormat::Mp3 => {
            command.args([
                "-c:a",
                "libmp3lame",
                "-b:a",
                "320k",
                "-id3v2_version",
                "3",
                "-f",
                "mp3",
            ]);
        }
        AudioDeliveryFormat::Wav => {
            command.args(["-c:a", "pcm_s24le", "-ar", "48000", "-f", "wav"]);
        }
        AudioDeliveryFormat::Bwf => {
            let description = format!(
                "Coquerythmo stem: {title}; language: {}",
                display_language(options.language_name)
            );
            command
                .args([
                    "-c:a",
                    "pcm_s24le",
                    "-ar",
                    "48000",
                    "-write_bext",
                    "1",
                    "-rf64",
                    "auto",
                ])
                .arg("-metadata")
                .arg("originator=Coquerythmo")
                .arg("-metadata")
                .arg(format!("description={description}"))
                .arg("-metadata")
                .arg("coding_history=A=PCM,F=48000,W=24")
                .args(["-f", "wav"]);
        }
    }

    if let Some(duration_frames) = options.duration_frames {
        command
            .arg("-t")
            .arg(format_decimal(duration_frames as f64 / fps));
    }

    let mut child = command
        .args(["-nostats", "-v", "warning", "-y"])
        .arg(&temporary)
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| format!("Cannot start FFmpeg audio export: {error}"))?;

    let stderr_thread = child.stderr.take().map(|mut stderr| {
        std::thread::spawn(move || {
            let mut details = String::new();
            let _ = stderr.read_to_string(&mut details);
            details
        })
    });

    let status = loop {
        if cancel.load(Ordering::Relaxed) {
            let _ = child.kill();
            let _ = child.wait();
            let _ = stderr_thread.and_then(|thread| thread.join().ok());
            let _ = std::fs::remove_file(&temporary);
            return Err(DELIVERY_EXPORT_CANCELLED_MESSAGE.to_string());
        }
        match child.try_wait() {
            Ok(Some(status)) => break status,
            Ok(None) => {}
            Err(error) => {
                let _ = child.kill();
                let _ = child.wait();
                let _ = stderr_thread.and_then(|thread| thread.join().ok());
                let _ = std::fs::remove_file(&temporary);
                return Err(format!("Cannot wait for FFmpeg audio export: {error}"));
            }
        }
        std::thread::sleep(Duration::from_millis(40));
    };
    let stderr = stderr_thread
        .and_then(|thread| thread.join().ok())
        .unwrap_or_default();

    if !status.success() {
        let _ = std::fs::remove_file(&temporary);
        let details = stderr.trim();
        return if details.is_empty() {
            Err("FFmpeg audio export failed".to_string())
        } else {
            Err(format!("FFmpeg audio export failed: {details}"))
        };
    }

    replace_output(&temporary, output)
}

pub fn export_mp3_audio(
    project: &Project,
    fps: f64,
    input: &Path,
    output: &Path,
    track: AudioTrackKind,
    language_name: &str,
    cancel: &AtomicBool,
) -> Result<(), String> {
    export_audio(
        project,
        fps,
        input,
        output,
        &AudioExportOptions::new(AudioDeliveryFormat::Mp3, track, language_name),
        cancel,
    )
}

pub fn export_wav_audio(
    project: &Project,
    fps: f64,
    input: &Path,
    output: &Path,
    track: AudioTrackKind,
    language_name: &str,
    cancel: &AtomicBool,
) -> Result<(), String> {
    export_audio(
        project,
        fps,
        input,
        output,
        &AudioExportOptions::new(AudioDeliveryFormat::Wav, track, language_name),
        cancel,
    )
}

/// Export several mono or multichannel inputs as separate Broadcast Wave
/// stems. This is intentionally a batch of files rather than a proprietary
/// container, which keeps each stem independently usable by a DAW.
pub fn export_bwf_stems(
    project: &Project,
    fps: f64,
    stems: &[AudioStemExport<'_>],
    cancel: &AtomicBool,
) -> Result<(), String> {
    for stem in stems {
        let options = AudioExportOptions {
            format: AudioDeliveryFormat::Bwf,
            track: stem.track,
            language_name: stem.language_name,
            stem_name: stem.stem_name,
            duration_frames: stem.duration_frames,
        };
        export_audio(project, fps, stem.input, stem.output, &options, cancel)?;
    }
    Ok(())
}

/// Last meaningful project frame, suitable as an explicit audio delivery
/// duration when a caller wants all stems to have equal length.
pub fn project_delivery_duration_frames(project: &Project) -> i64 {
    project
        .lines()
        .map(RythmoLine::end_frame)
        .chain(project.markers().iter().map(|marker| marker.frame))
        .max()
        .unwrap_or(1)
        .max(1)
}

fn audio_delivery_filter(offset_frames: i64, fps: f64, duration_frames: Option<i64>) -> String {
    let offset_seconds = offset_frames as f64 / fps;
    let mut filters = Vec::<String>::new();
    if offset_frames > 0 {
        let delay_ms = (offset_seconds * 1000.0).round().max(0.0) as i64;
        filters.push(format!("adelay={delay_ms}:all=1"));
    } else if offset_frames < 0 {
        filters.push(format!("atrim=start={}", format_decimal(-offset_seconds)));
    }
    if let Some(duration_frames) = duration_frames {
        let duration = format_decimal(duration_frames as f64 / fps);
        filters.push(format!("apad=whole_dur={duration}"));
        filters.push(format!("atrim=duration={duration}"));
    }
    filters.push("asetpts=PTS-STARTPTS".to_string());
    filters.join(",")
}

fn format_decimal(value: f64) -> String {
    let mut value = format!("{value:.9}");
    while value.ends_with('0') {
        value.pop();
    }
    if value.ends_with('.') {
        value.push('0');
    }
    value
}

fn temporary_audio_path(output: &Path, format: AudioDeliveryFormat) -> std::path::PathBuf {
    let parent = output.parent().unwrap_or_else(|| Path::new("."));
    let filename = output
        .file_name()
        .and_then(|name| name.to_str())
        .filter(|name| !name.is_empty())
        .unwrap_or("audio");
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_nanos())
        .unwrap_or(0);
    parent.join(format!(
        ".{filename}.{}.{}.part.{}",
        std::process::id(),
        stamp,
        format.extension()
    ))
}

fn replace_output(temporary: &Path, output: &Path) -> Result<(), String> {
    if output.exists() {
        std::fs::remove_file(output)
            .map_err(|error| format!("Cannot replace {}: {error}", output.display()))?;
    }
    if let Err(error) = std::fs::rename(temporary, output) {
        let _ = std::fs::remove_file(temporary);
        return Err(format!(
            "Cannot finalize audio delivery {}: {error}",
            output.display()
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::export::ProjectData;
    use crate::project::ProjectSettings;
    use crate::rythmo_line::RythmoMarker;

    fn sample_project() -> Project {
        let mut project = Project::new();
        let second = project.add_line_full_with_voice_actors(
            48,
            24,
            0.5,
            "Au revoir, \"Bob\"".to_string(),
            "Bob & Co".to_string(),
            [0.0, 0.0, 1.0, 1.0],
            vec!["Jean Dupont".to_string()],
        );
        project.add_line_full(
            24,
            24,
            0.25,
            "Bonjour\nle monde".to_string(),
            "Alice <Lead>".to_string(),
            [1.0, 0.0, 0.0, 1.0],
        );
        project.get_line_mut(second).unwrap().note = "Voix off".to_string();
        project.add_marker(RythmoMarker {
            kind: MarkerKind::Boucle,
            frame: 0,
        });
        project.add_marker(RythmoMarker {
            kind: MarkerKind::Boucle,
            frame: 48,
        });
        project.add_marker(RythmoMarker {
            kind: MarkerKind::Out,
            frame: 96,
        });
        project
    }

    #[test]
    fn json_uses_project_data_and_requested_fps() {
        let project = sample_project();
        let json = json_document(&project, 24.0).unwrap();
        let data: ProjectData = serde_json::from_str(&json).unwrap();
        assert_eq!(data.source_fps, 24.0);
        assert_eq!(data.lines.len(), 2);
        assert_eq!(data.lines[0].text, "Au revoir, \"Bob\"");
        assert!(data.languages.is_empty());
        assert!(data.active_language_id.is_none());
    }

    #[test]
    fn srt_is_chronological_and_uses_millisecond_timecodes() {
        let project = sample_project();
        let srt = srt_document(&project, 24.0).unwrap();
        assert!(srt.contains("1\r\n00:00:01,000 --> 00:00:02,000\r\nBonjour\r\nle monde"));
        assert!(srt.contains("2\r\n00:00:02,000 --> 00:00:03,000"));
        assert!(srt.ends_with("\r\n\r\n"));
    }

    #[test]
    fn ass_keeps_role_names_colors_and_escapes_override_text() {
        let mut project = sample_project();
        let id = project.add_line_full(
            80,
            8,
            0.5,
            "{unsafe}, ok".to_string(),
            "Alice <Lead>".to_string(),
            [1.0, 0.0, 0.0, 1.0],
        );
        project.get_line_mut(id).unwrap().text = "{unsafe}, ok".to_string();
        let ass = ass_document(&project, 24.0, "Français").unwrap();
        assert!(ass.contains("Title: Coquerythmo - Français"));
        assert!(ass.contains("&H000000FF"));
        assert!(ass.contains("Alice <Lead>"));
        assert!(ass.contains("\\{unsafe\\}, ok"));
    }

    #[test]
    fn detx_contains_roles_tracks_markers_and_xml_escaping() {
        let project = sample_project();
        let detx = detx_document(&project, 24.0, "Français & Québec").unwrap();
        assert!(detx.starts_with("<?xml version=\"1.0\" encoding=\"UTF-8\"?>"));
        assert!(detx.contains("Français &amp; Québec"));
        assert!(detx.contains("name=\"Alice &lt;Lead&gt;\""));
        assert!(detx.contains("<loop timecode=\"00:00:02:00\" />"));
        assert!(detx.contains("voice=\"off\""));
        assert!(detx.contains("<text>Au revoir, &quot;Bob&quot;</text>"));
    }

    #[test]
    fn detx_roundtrips_through_existing_importer() {
        let project = sample_project();
        let detx = detx_document(&project, 24.0, "fr").unwrap();
        let path = std::env::temp_dir().join(format!(
            "coquerythmo_delivery_{}_roundtrip.detx",
            std::process::id()
        ));
        std::fs::write(&path, detx).unwrap();
        let restored = crate::export::import_cappela(&path, 24.0).unwrap();
        let _ = std::fs::remove_file(path);
        assert_eq!(restored.lines.len(), 2);
        assert_eq!(restored.lines[0].text, "Bonjour le monde");
        assert_eq!(restored.lines[0].start_frame, 24);
        assert_eq!(restored.lines[0].duration_frames, 24);
        assert_eq!(restored.markers.len(), 2);
    }

    #[test]
    fn csv_is_rfc_4180_quoted_and_assigns_loops() {
        let project = sample_project();
        let csv = cross_reference_csv_document(&project, 24.0, "fr").unwrap();
        assert!(csv.starts_with('\u{feff}'));
        assert!(csv.contains("fr,1,00:00:01:00,00:00:02:00"));
        assert!(csv.contains("fr,2,00:00:02:00,00:00:03:00"));
        assert!(csv.contains("\"Au revoir, \"\"Bob\"\"\""));
        assert!(csv.contains("\"Bonjour\nle monde\""));
    }

    #[test]
    fn pdf_reports_are_valid_minimal_documents() {
        let project = sample_project();
        let cross_reference = cross_reference_pdf_bytes(&project, 24.0, "Français").unwrap();
        let presence = presence_grid_pdf_bytes(&project, 24.0, "Français").unwrap();
        assert_pdf_structure(&cross_reference);
        assert_pdf_structure(&presence);
        let cross_text = String::from_utf8_lossy(&cross_reference);
        let presence_text = String::from_utf8_lossy(&presence);
        assert!(cross_text.contains("Dialogue cross-reference"));
        assert!(cross_text.contains("Fran\\347ais"));
        assert!(presence_text.contains("Loop presence grid"));
        assert!(presence_text.contains("(X) Tj"));
    }

    #[test]
    fn unicode_pdf_text_uses_shaped_masks_and_preserves_actual_text() {
        let japanese = "日本語の台詞";
        let arabic = "حوار باللغة العربية";
        assert!(pdf_text_width(arabic, 10.0) < 180.0);
        assert_eq!(wrap_pdf_text(arabic, 180.0, 10.0, 3).len(), 1);
        let mut page = PdfCanvas::default();
        page.text(24.0, 100.0, 10.0, false, japanese);
        page.text(24.0, 80.0, 10.0, true, arabic);

        assert_eq!(page.image_masks.len(), 2);
        assert!(page
            .image_masks
            .iter()
            .all(|image| image.packed_bits.iter().any(|byte| *byte != 0)));
        assert!(page
            .content
            .contains(&format!("/ActualText <{}>", pdf_utf16_hex(japanese))));
        assert!(page
            .content
            .contains(&format!("/ActualText <{}>", pdf_utf16_hex(arabic))));
        assert!(!page.content.contains("(?) Tj"));

        let pdf = build_pdf(&[page]);
        assert_pdf_structure(&pdf);
        let pdf_text = String::from_utf8_lossy(&pdf);
        assert!(pdf_text.contains("/Subtype /Image"));
        assert!(pdf_text.contains("/ImageMask true"));
        assert!(pdf_text.contains("/XObject << /Im1"));
    }

    #[test]
    fn unicode_report_pdfs_keep_japanese_and_arabic_content() {
        let mut project = Project::new();
        project.add_line_full(
            0,
            24,
            0.25,
            "こんにちは、世界。これは日本語の台詞です。".to_string(),
            "美咲".to_string(),
            [0.8, 0.3, 0.4, 1.0],
        );
        project.add_line_full(
            24,
            24,
            0.5,
            "مرحباً بالعالم، هذا حوار باللغة العربية.".to_string(),
            "ليلى".to_string(),
            [0.2, 0.5, 0.9, 1.0],
        );
        project.add_marker(RythmoMarker {
            kind: MarkerKind::Boucle,
            frame: 0,
        });
        project.add_marker(RythmoMarker {
            kind: MarkerKind::Out,
            frame: 48,
        });

        let cross_reference = cross_reference_pdf_bytes(&project, 24.0, "日本語 / العربية")
            .expect("Unicode cross-reference PDF");
        let presence = presence_grid_pdf_bytes(&project, 24.0, "日本語 / العربية")
            .expect("Unicode presence-grid PDF");
        for pdf in [&cross_reference, &presence] {
            assert_pdf_structure(pdf);
            let text = String::from_utf8_lossy(pdf);
            assert!(text.contains("/ImageMask true"));
            assert!(text.contains(pdf_utf16_hex("日本語 / العربية").trim_start_matches("FEFF")));
            assert!(!text.contains("(??) Tj"));
        }

        if let Some(output_dir) = std::env::var_os("COQUERYTHMO_PDF_TEST_OUTPUT") {
            let output_dir = std::path::PathBuf::from(output_dir);
            std::fs::create_dir_all(&output_dir).unwrap();
            std::fs::write(
                output_dir.join("unicode-cross-reference.pdf"),
                cross_reference,
            )
            .unwrap();
            std::fs::write(output_dir.join("unicode-presence-grid.pdf"), presence).unwrap();
        }
    }

    fn assert_pdf_structure(pdf: &[u8]) {
        assert!(pdf.starts_with(b"%PDF-1.4"));
        assert!(pdf.ends_with(b"%%EOF\n"));
        let text = String::from_utf8_lossy(pdf);
        let startxref_marker = text.rfind("startxref\n").unwrap();
        let xref_offset: usize = text[startxref_marker + "startxref\n".len()..]
            .lines()
            .next()
            .unwrap()
            .parse()
            .unwrap();
        assert_eq!(&pdf[xref_offset..xref_offset + 4], b"xref");
        assert!(text.contains("/Type /Catalog"));
        assert!(text.contains("/Type /Page "));
        assert!(text.contains("/BaseFont /Helvetica"));
    }

    #[test]
    fn presence_spans_stop_at_next_loop_or_out() {
        let project = sample_project();
        let spans = loop_spans(&project);
        assert_eq!(spans.len(), 2);
        assert_eq!((spans[0].start, spans[0].end), (0, 48));
        assert_eq!((spans[1].start, spans[1].end), (48, 96));
    }

    #[test]
    fn authored_loop_numbering_does_not_gain_a_synthetic_zero_marker() {
        let mut project = Project::new();
        project.add_marker(RythmoMarker {
            kind: MarkerKind::Boucle,
            frame: 24,
        });
        project.add_marker(RythmoMarker {
            kind: MarkerKind::Boucle,
            frame: 48,
        });
        assert_eq!(loop_starts(&project), vec![24, 48]);
        let spans = loop_spans(&project);
        assert_eq!(spans[0].number, 1);
        assert_eq!((spans[0].start, spans[0].end), (24, 48));
    }

    #[test]
    fn audio_filter_applies_positive_and_negative_offsets() {
        assert_eq!(
            audio_delivery_filter(24, 24.0, None),
            "adelay=1000:all=1,asetpts=PTS-STARTPTS"
        );
        assert_eq!(
            audio_delivery_filter(-12, 24.0, Some(48)),
            "atrim=start=0.5,apad=whole_dur=2.0,atrim=duration=2.0,asetpts=PTS-STARTPTS"
        );
    }

    #[test]
    fn audio_export_honors_pre_cancel_without_starting_ffmpeg() {
        let mut project = Project::new();
        let mut settings = ProjectSettings::default();
        settings.source_audio_offset_frames = 10;
        settings.instrumental_audio_offset_frames = -10;
        project.set_settings(settings);
        let cancel = AtomicBool::new(true);
        let result = export_mp3_audio(
            &project,
            24.0,
            Path::new("does-not-exist.wav"),
            Path::new("must-not-be-created.mp3"),
            AudioTrackKind::Original,
            "fr",
            &cancel,
        );
        assert_eq!(result.unwrap_err(), DELIVERY_EXPORT_CANCELLED_MESSAGE);
    }

    #[test]
    fn invalid_fps_is_rejected_for_all_document_exports() {
        let project = sample_project();
        assert!(srt_document(&project, 0.0).is_err());
        assert!(ass_document(&project, f64::NAN, "fr").is_err());
        assert!(detx_document(&project, -1.0, "fr").is_err());
        assert!(cross_reference_pdf_bytes(&project, 0.0, "fr").is_err());
    }
}
